app:
  message: This in the propety file fo the ${spring.application.name}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/devjavajr
    username: postgres
    password: admin
    platform: postgres

  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: true
    hibernate:
      format_sql: true
#      ddl-auto: create