app:
  message: This in the propety file fo the ${spring.application.name}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    open-in-view: true

    properties:
      hibernate:
        format_sql: true